format_version: '23'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: android
app:
  envs:
  - TEST_SHARD_COUNT: 2
  - PROJECT_LOCATION: "./"
    opts:
      is_expand: false
  - MODULE: app
    opts:
      is_expand: false
pipelines:
  run_tests:
    workflows: {}
workflows:
  build_aab:
    steps:
    - git-clone@8: {}
    - install-missing-android-tools@3:
        inputs:
        - gradlew_path: "$PROJECT_LOCATION/gradlew"
    - gradle-runner@4:
        inputs:
        - build_root_directory: bundleRelease
    - sign-apk@2:
        run_if: '{{getenv "BITRISEIO_ANDROID_KEYSTORE_URL" | ne ""}}'
    - deploy-to-bitrise-io@2: {}
  build_debug_apk:
    steps:
    - git-clone@8: {}
    - install-missing-android-tools@3:
        inputs:
        - gradlew_path: "$PROJECT_LOCATION/gradlew"
    - gradle-runner@4: {}
    - sign-apk@2:
        run_if: '{{getenv "BITRISEIO_ANDROID_KEYSTORE_URL" | ne ""}}'
    - deploy-to-bitrise-io@2: {}
  add_key:
    steps:
    - script@1:
        inputs:
        - content: "#!/bin/bash

            set -e


            # Путь для keystore

            KEYSTORE_PATH=\"$BITRISE_SOURCE_DIR/my-release-key.jks\"


            # Параметры берём из Secrets Bitrise

            KEYSTORE_PASSWORD=\"HFGHFDGDSGDSG\"

            KEY_PASSWORD=\"HFGHFDGDSGDSG\"

            KEY_ALIAS=\"dfdsgdshgdhds\"

            DNAME=\"${DNAME:-CN=FSGSD, OU=RE, O=EF, L=City, S=Region, C=AG}\"


            # Проверяем, существует ли keystore

            if [ -f \"$KEYSTORE_PATH\" ]; then

            \  echo \"✅ Keystore уже существует: $KEYSTORE_PATH\"

            else

            \  echo \"⚙️ Keystore не найден. Создаём новый...\"

            \  keytool -genkeypair -v \\

            \    -keystore \"$KEYSTORE_PATH\" \\

            \    -storepass \"$KEYSTORE_PASSWORD\" \\

            \    -keypass \"$KEY_PASSWORD\" \\

            \    -keyalg RSA -keysize 2048 -validity 10000 \\

            \    -alias \"$KEY_ALIAS\" \\

            \    -dname \"$DNAME\"

            \  echo \"✅ Keystore создан: $KEYSTORE_PATH\"

            fi


            # Копируем в директорию deploy для скачивания через артефакты

            mkdir -p \"$BITRISE_DEPLOY_DIR\"

            cp \"$KEYSTORE_PATH\" \"$BITRISE_DEPLOY_DIR/\"


            echo \"📦 Keystore готов и доступен для скачивания как артефакт\""
    - deploy-to-bitrise-io@2: {}
meta:
  bitrise.io:
    stack: osx-xcode-26.0.x
    machine_type_id: g2.mac.large